# Generated by Django 2.0.7 on 2023-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkThat',
            field=models.BooleanField(default=False),
        ),
    ]
